pipeline{
    agent any

    tools { maven 'M2_HOME'}
    
    stages{
        stage("Unit Test"){
            steps{
                sh 'mvn clean'
                sh 'mvn compile'
                sh 'mvn test'
            }

            }
        
        stage('Build'){
            steps{
                sh 'mvn build'
            }
            
        }
    }
}