pipeline{
    agent any

    tools { maven 'M2_HOME'}
    
    stages{
        stage("Unit Test"){
            steps{
                sh 'mvn clean'
                sh 'mvn compile'
                sh 'mvn test'
            }

            }
        
        stage('Build'){
            steps{
                sh 'mvn build'
            }
        }

        stage('ECR authentication'){
            steps{
                sh 'aws ecr get-login-password --region us-east-1 | \
                docker login --username AWS --password-stdin 211125431540.dkr.ecr.us-east-1.amazonaws.com'
            }
        }
    }
}